@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMjRkZWQ1MS01NTJlLTRkMDItYjUwYS04YTQwYzZiMDNhMmQiLCJ1bmlxdWVfbmFtZSI6ImUyNGRlZDUxLTU1MmUtNGQwMi1iNTBhLThhNDBjNmIwM2EyZCIsImp0aSI6IjZkZTU1MTUwLTY4OGMtNDUzMS1iMDg3LTM1NjhkYTI3NTdkMCIsImlhdCI6IjE1MzM3MjI3MDU3NTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTUzMzcyMjcwNSwiZXhwIjoxNTMzNzI0NTA1LCJpc3MiOiJkc2hvcC1pZGVudGl0eS1zZXJ2aWNlIn0.DS9tDzCR5LEmrM7hG_RVv1geA4SgJ58AY9iFnLGndl8
@customerId = xxxxxxxxxxxxxxxxxx
@operationId = xxxxxxxxxxxxxxxxxx
@productId = 87d85722-47a9-4569-bea4-b92ae6243053
@orderId = 9765f00c-fa4a-4aec-9d1e-7a7ecb910b70

### ================= IDENTITY API =======================
POST http://localhost:5002/sign-up
content-type: application/json

{
	"email": "user1@mailinator.com",
	"password": "123456",
	"role": "admin"
}

###
POST http://localhost:5002/sign-in
content-type: application/json

{
	"email": "user1@mailinator.com",
	"password": "123456"
}


### ================= CART API =======================
GET http://localhost:5000/cart
authorization: Bearer {{token}}

###
POST http://localhost:5000/cart/items
authorization: Bearer {{token}}
content-type: application/json

{
	"productId": "{{productId}}",
	"quantity": 2
}

###
DELETE http://localhost:5000/cart/items/{{productId}}
authorization: Bearer {{token}}

### 
DELETE http://localhost:5000/cart/clear
authorization: Bearer {{token}}


### ================= CUSTOMERS API =======================
GET http://localhost:5000/customers
authorization: Bearer {{token}}

###
GET http://localhost:5000/customers/{{customerId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/customers
authorization: Bearer {{token}}
content-type: application/json

{
	"firstName": "John",
	"lastName": "Smith",
	"address": "DNC 3",
	"country": "Poland"
}


### ================= OPERATIONS API =======================
GET http://localhost:5000/operations/{{operationId}}
authorization: Bearer {{token}}

### ================= ORDERS API =======================
GET http://localhost:5000/orders
authorization: Bearer {{token}}

###
GET http://localhost:5000/orders/{{orderId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/orders
authorization: Bearer {{token}}
content-type: application/json

{
}

###
POST http://localhost:5000/orders/{{orderId}}/complete
authorization: Bearer {{token}}
content-type: application/json

{
}

###
DELETE http://localhost:5000/orders
authorization: Bearer {{token}}


### ================= PRODUCTS API =======================

GET http://localhost:5000/products
authorization: Bearer {{token}}

###
GET http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/products
authorization: Bearer {{token}}
content-type: application/json

{
	"name": "Product X",
	"description": "Awesome product",
	"vendor": "Product Owner",
	"price": 2500
}

###
POST http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}
content-type: application/json

{
	"name": "Updated Product X",
	"description": "Awesome updated product",
	"price": 2501
}

###
DELETE http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}