@token = xxxxxxxxxxxxxxxxxx
@productId = xxxxxxxxxxxxxxxxxx
@orderId = xxxxxxxxxxxxxxxxxx

POST http://localhost:5002/sign-up
content-type: application/json

{
	"email": "dnc-wdi@mailinator.com",
	"password": "secret"
}

###
POST http://localhost:5002/sign-in
content-type: application/json

{
	"email": "dnc-wdi@mailinator.com",
	"password": "secret"
}

###
POST http://localhost:5000/customers
authorization: Bearer {{token}}
content-type: application/json

{
	"firstName": "John",
	"lastName": "Smith",
	"address": "DNC 3",
	"country": "Poland"
}

###
GET http://localhost:5000/cart
authorization: Bearer {{token}}

###
GET http://localhost:5000/products
authorization: Bearer {{token}}

###
POST http://localhost:5000/cart/items
authorization: Bearer {{token}}
content-type: application/json

{
	"productId": "{{productId}}",
	"quantity": 5
}

###
GET http://localhost:5000/orders
authorization: Bearer {{token}}

###
POST http://localhost:5000/orders
authorization: Bearer {{token}}
content-type: application/json

{
}

###
POST http://localhost:5000/orders/{{orderId}}/complete
authorization: Bearer {{token}}
content-type: application/json

{
}