@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTg5ZDc1NzNjZmI0MTMxOTlhMmZhNThiOWVmNmVmYiIsInVuaXF1ZV9uYW1lIjoiYjE4OWQ3NTczY2ZiNDEzMTk5YTJmYTU4YjllZjZlZmIiLCJqdGkiOiJlMDJlNzYyMS00MmRkLTQ3ZGMtYTU5ZC02YTdlNDJkNzgxMDQiLCJpYXQiOiIxNTM2MDYxNzM1MTM0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTUzNjA2MTczNSwiZXhwIjoxNTM2MDYzNTM1LCJpc3MiOiJkc2hvcC1pZGVudGl0eS1zZXJ2aWNlIn0.SI4-Q5ED6rZ37iOxJYstxQbDfkjXeUPbt3lf8FOLGL8
@customerId = xxxxxxxxxxxxxxxxxx
@operationId = xxxxxxxxxxxxxxxxxx
@productId = xxxxxxxxxxxxxxxxxx
@orderId = xxxxxxxxxxxxxxxxxx

### ================= IDENTITY API =======================
POST http://localhost:5002/sign-up
content-type: application/json

{
	"email": "user1@mailinator.com",
	"password": "secret",
	"role": "user"
}

###
POST http://localhost:5002/sign-in
content-type: application/json

{
	"email": "user1@mailinator.com",
	"password": "secret"
}


### ================= CART API =======================
GET http://localhost:5000/cart
authorization: Bearer {{token}}

###
POST http://localhost:5000/cart/items
authorization: Bearer {{token}}
content-type: application/json

{
	"productId": "{{productId}}",
	"quantity": 2
}

###
DELETE http://localhost:5000/cart/items/{{productId}}
authorization: Bearer {{token}}

### 
DELETE http://localhost:5000/cart/clear
authorization: Bearer {{token}}


### ================= CUSTOMERS API =======================
GET http://localhost:5000/customers
authorization: Bearer {{token}}

###
GET http://localhost:5000/customers/{{customerId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/customers
authorization: Bearer {{token}}
content-type: application/json

{
	"firstName": "John",
	"lastName": "Smith",
	"address": "DNC 3",
	"country": "Poland"
}


### ================= OPERATIONS API =======================
GET http://localhost:5000/operations/{{operationId}}
authorization: Bearer {{token}}

### ================= ORDERS API =======================
GET http://localhost:5000/orders
authorization: Bearer {{token}}

###
GET http://localhost:5000/orders/{{orderId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/orders
authorization: Bearer {{token}}
content-type: application/json

{
}

###
POST http://localhost:5000/orders/{{orderId}}/complete
authorization: Bearer {{token}}
content-type: application/json

{
}

###
DELETE http://localhost:5000/orders
authorization: Bearer {{token}}


### ================= PRODUCTS API =======================

GET http://localhost:5000/products
authorization: Bearer {{token}}

###
GET http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}

###
POST http://localhost:5000/products
authorization: Bearer {{token}}
content-type: application/json

{
	"name": "Product X",
	"description": "Awesome product",
	"vendor": "Product Owner",
	"price": 2500
}

###
POST http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}
content-type: application/json

{
	"name": "Updated Product X",
	"description": "Awesome updated product",
	"price": 2501
}

###
DELETE http://localhost:5000/products/{{productId}}
authorization: Bearer {{token}}